---
- name: Add EPEL repository
  yum: name=epel-release

#Since firewalld is mandatory
- name: Install firewalld, Java, JNA
  become: true
  yum: 
    name: ['firewalld', 'java-1.8.0-openjdk', 'jna']
    state: latest

- name: Install Python PIP, wget, curl, jemalloc, unzip
  yum:
    name: ['python-pip','wget','curl','jemalloc','unzip','jq','pssh']
    state: latest

- name: Install perf monitoring tools
  yum:
    name: ['trafshow','sysstat','net-tools','iotop','dstat','htop','strace'] 
    state: latest

- name: Unarchive JCE in /tmp
  become: yes
  unarchive: src=jce_policy-8.zip dest=/tmp mode=0755
  tags: install

- name: Install JCE in <JDK>/jre/lib/security
  become: yes
  shell: cp /tmp/UnlimitedJCEPolicyJDK8/*.jar /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.*/jre/lib/security
  tags: install
